M  git/.git_templates/hooks/pre-commit: remove shell trap from script

diff --git a/git/.git_templates/hooks/pre-commit b/git/.git_templates/hooks/pre-commit
--- a/git/.git_templates/hooks/pre-commit
+++ b/git/.git_templates/hooks/pre-commit
@@ -7,17 +7,14 @@ exclude_dirs="${EXCLUDE_DIRS:-static/pico static/htmx static/hyperscript}"
 
 # Check if there are any changes in the repo
 if [[ -n $(git status --porcelain) ]]; then
-    echo "Changes detected, running ctags..."
-    trap 'rm -f "$$.tags"; echo "ctags generation failed. Temporary file cleaned up."' EXIT
+  echo "Changes detected, running ctags..."
 
-    if ! git ls-files | grep -v -E "^(${exclude_dirs// /|})" | \
-         ctags --tag-relative -L - -f"$$.tags"; then
-        echo "ctags command failed. Check if ctags is installed and the file patterns are correct."
-        exit 1
-    fi
+  if ! git ls-files | grep -v -E "^(${exclude_dirs// /|})" |
+    ctags --tag-relative -L - -f"$$.tags"; then
+    echo "ctags command failed. Check if ctags is installed and the file patterns are correct."
+    exit 1
+  fi
 
-    mv "$$.tags" "tags"
-    echo "ctags generated successfully."
-else
-    echo "No changes detected, skipping ctags generation."
+  mv "$$.tags" "tags"
+  echo "ctags generated successfully."
 fi
