fix: add ability to call local pre-commit hooks
	modified:   git/.git_global/hooks/pre-commit
	modified:   git/.git_templates/hooks/pre-commit

diff --git a/git/.git_global/hooks/pre-commit b/git/.git_global/hooks/pre-commit
--- a/git/.git_global/hooks/pre-commit
+++ b/git/.git_global/hooks/pre-commit
@@ -25,3 +25,10 @@ if [[ -n $(git status --porcelain) ]]; then
   mv "$$.tags" "tags"
   echo "ctags generated successfully."
 fi
+
+if [ -f .git/hooks/pre-commit ]; then
+  if ! .git/hooks/pre-commit "$@"; then
+    echo "local pre-commit hook failed"
+    exit 1
+  fi
+fi
